### ISSUE TITLE
Use of vocabulary-scoped identifiers in `@values`

### ISSUE THREAD

**Issue by Peeja** [m-ld/m-ld-spec#77]
This looks like a bug to me, but I also could easily be misunderstanding the intended semantics. I'm not sure how to characterize it, so by all means, please retitle this issue if you can put it more usefully. 😃 

---

Given the following data:

```json
[
  {
    "@id": "http://www.example.com/foo",
    "aProperty": "existing-value"
  },
  {
    "@id": "http://www.example.com/bar",
    "aProperty": "another-existing-value"
  }
]
```

I expected the query:

```json
{
  "@construct": {
    "@id": "?id",
    "?property": "?value"
  },
  "@where": {
    "@graph": {
      "@id": "?id",
      "?property": "?value"
    },
    "@values": [
      {
        "?id": "http://www.example.com/foo"
      }
    ]
  }
}
```

to return:

```json
[
  {
    "@id": "http://www.example.com/foo",
    "aProperty": "existing-value"
  }
]
```

but instead it returns `[]`. ([playground](https://www.m-ld.org/playground/#txn=%5B%7B%22%40id%22%3A%22http%3A%2F%2Fwww.example.com%2Ffoo%22%2C%22aProperty%22%3A%22existing-value%22%7D%2C%7B%22%40id%22%3A%22http%3A%2F%2Fwww.example.com%2Fbar%22%2C%22aProperty%22%3A%22another-existing-value%22%7D%5D&query=%7B%22%40construct%22%3A%7B%22%40id%22%3A%22%3Fid%22%2C%22%3Fproperty%22%3A%22%3Fvalue%22%7D%2C%22%40where%22%3A%7B%22%40graph%22%3A%7B%22%40id%22%3A%22%3Fid%22%2C%22%3Fproperty%22%3A%22%3Fvalue%22%7D%2C%22%40values%22%3A%5B%7B%22%3Fid%22%3A%22http%3A%2F%2Fwww.example.com%2Ffoo%22%7D%5D%7D%7D))

A similar `@select` query also yields `[]`. ([playground](https://www.m-ld.org/playground/#txn=%5B%7B%22%40id%22%3A%22http%3A%2F%2Fwww.example.com%2Ffoo%22%2C%22aProperty%22%3A%22existing-value%22%7D%2C%7B%22%40id%22%3A%22http%3A%2F%2Fwww.example.com%2Fbar%22%2C%22aProperty%22%3A%22another-existing-value%22%7D%5D&query=%7B%22%40select%22%3A%5B%22%3Fid%22%2C%22%3Fproperty%22%2C%22%3Fvalue%22%5D%2C%22%40where%22%3A%7B%22%40graph%22%3A%7B%22%40id%22%3A%22%3Fid%22%2C%22%3Fproperty%22%3A%22%3Fvalue%22%7D%2C%22%40values%22%3A%5B%7B%22%3Fid%22%3A%22http%3A%2F%2Fwww.example.com%2Ffoo%22%7D%5D%7D%7D))

For what it's worth, an empty `@values` successfully returns all of the data. ([playground](https://www.m-ld.org/playground/#txn=%5B%7B%22%40id%22%3A%22http%3A%2F%2Fwww.example.com%2Ffoo%22%2C%22aProperty%22%3A%22existing-value%22%7D%2C%7B%22%40id%22%3A%22http%3A%2F%2Fwww.example.com%2Fbar%22%2C%22aProperty%22%3A%22another-existing-value%22%7D%5D&query=%7B%22%40construct%22%3A%7B%22%40id%22%3A%22%3Fid%22%2C%22%3Fproperty%22%3A%22%3Fvalue%22%7D%2C%22%40where%22%3A%7B%22%40graph%22%3A%7B%22%40id%22%3A%22%3Fid%22%2C%22%3Fproperty%22%3A%22%3Fvalue%22%7D%2C%22%40values%22%3A%5B%5D%7D%7D))

---

The use case here is that I'm trying to read all of the existing triples for properties that I'm about to write, so that I can `@delete` the old values when I `@insert` the new values. I should be able to do the same thing with a bunch of reads and put them together, but that seems odd (but might be what I'll do for now, at least).

**Comment by gsvarovsky** [comment]
Suggested option https://github.com/m-ld/m-ld-spec/issues/77#issuecomment-929904927 is now available on the edge:

https://edge.js.m-ld.org/globals.html#vocabreference

`npm install @m-ld/m-ld@edge`

**Comment by Peeja** [comment]
> ```ts
> "?property": { "@vocab": key },
> ```

Ah! I'm following now. Yep, I like that too!

> Somewhere along the way this query has lost its `@union`, which means the `@graph` results (everything in the domain!) are being joined with the `@values`, which will drop the empty binding `{}`.

Yes, sorry, I should have been clearer there: I'm specifically trying to avoid this `@union`, because it grows with the size of the input—then `sparqlalgebrajs` turns it into a linked list, and then someone (not sure where it is) traverses that recursively, which blows the stack for large inputs (such as my initial data import in my first `write()`). I switched to a `read()` followed by a `write()` to avoid that, and then thought I could still avoid it with the `write()` above, but I was looking at the wrong tests when I thought it was working.

**Comment by gsvarovsky** [comment]
> ... which blows the stack for large inputs

I created another issue for this. In the meantime, hopefully the need for the `@union` or additional reads improves with the change of behaviour for `@delete`-with-variables plus `@insert`-without-variables, https://github.com/m-ld/m-ld-spec/issues/76#issuecomment-930051196
